### ISSUE TITLE
Detailed steps - AFF A800 - stale links in ONTAP Configuration Guide

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-systems#111]
Page: [Detailed steps - AFF A800](https://docs.netapp.com/us-en/ontap-systems/a800/install-detailed-guide.html)

At the very bottom of this page, there is a link to the [ONTAP Configuration Guide](https://library.netapp.com/ecm/ecm_download_file/ECMLP2862613), which contains many links to the outdated ONTAP 9 Doc Center and sections within it. Because the links to the topic within the Doc Center are malformed, they do not resolve to the new docs.netapp.com locations.

**Comment by thrisun** [comment]
Thanks Adam, Doug and I will take a look at the HW content collectively,

**Comment by netapp-martyh** [comment]
👍

**Comment by thrisun** [comment]
The ONTAP Configuration Guide was provided by Chris Lueth. I sent him an email regarding the issue.

**Comment by thrisun** [comment]
Hi Sundari,

Do we know the hit count on the configuration guide?  

My guess is the transition to github changed URL paths.  I think we can collapse the ONTAP administration into one URL - [ONTAP 9 Documentation (netapp.com)](https://docs.netapp.com/us-en/ontap/index.html).  The guide can be updated if the hit counts justify it.  But I’m working on some other items this week and this will have to wait until at least next week.

Chris


From: Naidu-P, Sundari <[sundari.naidu-p@netapp.com](mailto:sundari.naidu-p@netapp.com)> 
Sent: Monday, September 19, 2022 12:07 PM
To: Lueth, Chris <[Chris.Lueth@netapp.com](mailto:Chris.Lueth@netapp.com)>
Cc: Houser, Martin <[Martin.Houser@netapp.com](mailto:Martin.Houser@netapp.com)>; Thompson, Doug <[Doug.Thompson@netapp.com](mailto:Doug.Thompson@netapp.com)>
Subject: FW: [NetAppDocs/ontap-systems] Detailed steps - AFF A800 - stale links in ONTAP Configuration Guide (Issue #111)

Hi Chris,

Adam pointed out that some links the ONTAP Configuration Guide are malformed and not resolving correctly. I went through the Guide and top marks to you for knowing the AFF and FAS systems portal well but the following three links are bad and generating an insecure website message:

 

Given that our social media messaging to our customers is that we care about the safety and integrity of their data, I don’t think that this is a message that we want to send when they are configuring ONTAP. I am not going to pretend to know what the context of providing the above links are so, I did a search on each so that you can determine the URL you want to associate with the link:
•	[Search results (netapp.com)](https://docs.netapp.com/us-en/ontap/search.html?q=Network+and+LIF+management) for Network and LIF management
•	[Search results (netapp.com)](https://docs.netapp.com/us-en/ontap/search.html?q=Provision+for+NAS+protocols) for Provisioning for NAS protocols
•	[Search results (netapp.com)](https://docs.netapp.com/us-en/ontap/search.html?q=Provision+for+SAN+protocols) for Provisioning for SAN protocols

Hope this helps Chris,

Thripura Sundari Naidu-P., PMP
Senior Technical Writer, Information Engineering (IE) Content Services
NetApp Information Engineering
San Jose, CA USA (GMT -8)
408.822.6939 (direct)
[IE Intranet](http://prodops.netapp.com/busops/globalization/ie/) | [IE Community](http://live.netapp.com/community/prodops/ie) | [IE Master Schedule (VED)](http://ieapps01.eng.netapp.com/IEMaster/index.php)
