### ISSUE TITLE
psu locations

### ISSUE THREAD

**Issue by Rafael-Schippers** [NetAppDocs/ontap-systems#117]
Page: [Replace a power supply - FAS8300 and FAS8700](https://docs.netapp.com/us-en/ontap-systems/fas8300/power-supply-replace.html)

Any visual indicators for the location of PSU1 and PSU2 for node 1-2 would be helpfull

**Comment by dougthomp** [comment]
Hi Rafael:

Thank you for the feedback, it helps us improve out documentation.  

To help me understand your comment/request, in what context would that be helpful?  The reason I ask is because the documentation says the following in Step 2 in the PSU replacement doc:

"Identify the power supply you want to replace, based on console error messages or through the LEDs on the power supplies."

Cross-referencing the console message with the flashing LED on the PSU should identify the failed PSU. Was this not the case?  

Again, thanks for the feedback,
Doug

**Comment by dougthomp** [comment]
Hi again, Rafael:

I contacted Mechanical Engineering asking about labeling on the back of the system.  The PSUs do have a label over them (more between them), indicating which PSU is which.  

![image](https://user-images.githubusercontent.com/76076341/197294353-893dd86f-c744-4e4f-b1ca-3f681b58d1c5.png)

I'm closing this comment.

Thanks again for contacting us.

Doug
