### ISSUE TITLE
SSE feedback for Swap out a power supply - AFF A900

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap-systems#129]
Page: [Swap out a power supply - AFF A900](https://docs.netapp.com/us-en/ontap-systems/a900/power_supply_swap_out.html)
[Swap out a power supply.docx](https://github.com/NetAppDocs/ontap-systems/files/10340104/Swap.out.a.power.supply.docx)

**Comment by ericd-netapp** [comment]
Our SSE team met today to review PSU replacements on A900 and have attached some feedback. Please let us know if you have any questions.

**Comment by thrisun** [comment]
Thank you for your comments, Eric. I have assigned Doug to follow up on this.
Take care and keep safe!

**Comment by dougthomp** [comment]
Thanks Eric.  I'll incorporate the comments.

**Comment by dougthomp** [comment]
Comment on bullet #4.  The note is in preparation for Titanium PSU, which, if I recall, releases in a couple weeks.  I'm leaving that in the doc.  

Also leaving 3c as is. We've always had the step to unplug from the power source.  Something Mechanical recommended years ago.  I recall they were indicating it was a safety issue.  I'll double check with them on this.  If they give the ok to leave the cord plugged in, I'll remove the step to unplug it  

Step 4 - Mechanical also was vehement about calling the button terra cotta.  It was originally orange and the dug in their heels.  Also going to leave it as-is.  

Step 7a also leaving as-is, since we will still be removing the PSU from the power source.  (contingent on Mechanical's response to unplugging from the power source.

**Comment by dougthomp** [comment]
Removing 3C and 7a pert about plugging back into the power source.

**Comment by dougthomp** [comment]
Changes made.  They will go live on Monday 1/10.

**Comment by thrisun** [comment]
Thanks Doug, and please close the issue once the changes go live.

**Comment by dougthomp** [comment]
content is live
