### ISSUE TITLE
SSE Feedback:  Clarification and a bit more detailed requested for Slot priority/assignments

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap-systems#201]
### Page URL

https://docs.netapp.com/us-en/ontap-systems/c250/install-quick-guide.html

### Page title

Quick steps - AFF C250

### Summary

In both the A250 and C250 quick start guides in Stage 3 it gives 3 options on installing expansion cards in the controller.

The examples have 25Gbe host side network cards in Slot1, and a FC host network card in Slot2, and External storage cards in Slot1.

The problem with these examples are that slot priority is extremely important on this platform and that slot1 is the ONLY slot can be used for External storage (SAS or NVME).  This isn't really spelled out and can lead to issues down the road when/if the customer wants to expand.   It would be nice to have this written out and perhaps links to HWU for the rules.   maybe a line also to state that if the customer only has 1 card at time of installation, (either a Network or FC card), they need to put it in Slot 2.  (as per the HWU).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lisa** [comment]
Hi Eric, I get what you are saying for the C250 and A250. I think putting this note at the beginning of the Cable configuration-dependent options section will address the issue: "If your storage system did not come with an external shelf, but in the future, you might attach one, and if each controller has only one host network card, move the card from controller slot 1 to slot 2 before cabling your storage system. This prepares your storage system for the future shelf, since shelf adapter cards are only supported in controller slot 1. Slot priorities can be found in the <Hardware Universe link>."  When you said to point users to HWU for the rules, you meant the slot priorities? I'd also add this note to the new system install Detailed guides and Videos.

**Comment by ericd-netapp** [comment]
The only comment I'd make on that change is that if you have 1 expansion card that's either a FC card or NIC, the slot priority is always slot 2 first -- this is per the HWU.  Nothing should ever go into slot1 unless you have 2 cards.  And if you have 2 cards at time of installation, the FC card needs to go in slot 2 over the NIC.  And of course, if you have a card for storage expansion, then it must go in slot 1 no matter what.

**Comment by netapp-lisa** [comment]
Okay, I think you're saying we need to explain what is being shown in the quick start guides per HWU slot priorities, because it's not clear. How about this: "Note: Hardware Universe <link> slot priority for host network cards (FC or 25GbE) is slot 2. However, if you have both cards, the FC card goes in slot 2 and the 25GbE card goes in slot 1 (as shown below). If you have an external shelf, the storage card goes in slot 1, the only supported slot for shelves." 
<img width="513" alt="image" src="https://github.com/NetAppDocs/ontap-systems/assets/77256372/1dcd5f5b-0441-4f95-b0b0-a48b6e707174">

**Comment by ericd-netapp** [comment]
that looks good Lisa - I think this will help prevent systems with just a single non-storage based NIC going into slot 1.  I think it's a visual thing from the poster that was causing this; having some extra warnings will help!

**Comment by netapp-lisa** [comment]
Great! I'll add the note to the A250 and C250 Quick starts, Detailed steps, and Videos.
