### ISSUE TITLE
Where is the "standard" NS224 Drive Shelf  Cabling Guide?

### ISSUE THREAD

**Issue by amadorloureiro** [NetAppDocs/ontap-systems#73]
Page: [NS224 shelves](https://docs.netapp.com/us-en/ontap-systems/ns224/index.html)

We can find the following URL https://library.netapp.com/ecm/ecm_get_file/ECMLP2876580 but we cannot see if this is the latest version available of the PDF/PPT and not "usable" as a github doc.

Is the information in the link above available in some section of our documentation? If it is not, can that information be added to this section?

**Comment by netapp-lisa** [comment]
Hi, sorry for the delay in responding. The URL to the file you sent is the latest version, v1.3.1. This doc is owned and maintained by TME and lives on the field portal as a PowerPoint doc. However, since a login is needed to access it, to make accessibility easier - since it's meant for public use - a PDF version was moved out of the field portal and the link was provided via this doc in GitHub (https://docs.netapp.com/us-en/ontap-systems/ns224/cable-as-switch-attached.html). Since the original format of the doc is in PowerPoint, it can't be in GitHub. I get notifications when there's an update to the original doc in the field portal and I replace the file at the location of your URL. Just to be sure, I went to the field portal, did a search on the doc title, and see it's the same v1.3.1. Let me know if you have any other questions.

**Comment by amadorloureiro** [comment]
Hi Lisa,

Sounds good to me for now. Thanks a lot!!!

Regards,

Amador Loureiro
Technical Support Engineer
Technical Support Center

NetApp
***@***.******@***.***>

My normal working hours are Monday to Friday, 9:00 a.m. – 17:30 p.m. CEST.

For technical assistance on a new or existing case, please call:
* US & Canada 888-4-NETAPP // * EMEA/Europe  00-800-44-638277 // * Asia/Pacific  800-8008-0800

You may also get Support on the Web at http://mysupport.netapp.com<http://mysupport.netapp.com/>.

Everyone in the NetApp Technical Support Center is committed to providing the highest level of customer satisfaction.  If you believe that the level of support can be improved, please contact my manager, James Donnelly, at ***@***.******@***.***>

[A picture containing drawing  Description automatically generated]<https://www.netapp.com/us/index.aspx>

[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

**Comment by netapp-lisa** [comment]
You're welcome! Have a good weekend.
